config/routes.rb
LetsGetPro::Application.routes.draw do

  resources :friendships

  resources :search

  resources :jobshistories

  resources :curriculums

  resources :posts

  resources :companies

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/profile/:id',  to: 'users#show',:as => :profile, via:'get'
  match '/about', to:'static_pages#about', via:'get'

  root 'posts#index', action: 'home'

end

app/models/curriculum.rb
class Curriculum < ActiveRecord::Base
  belongs_to :user, :class_name => 'User',:foreign_key => 'user_id'
  has_many :jobshistories, :class_name => 'Jobshistory',:foreign_key => 'curr_id'
end

app/controllers/curriculums_controller.rb
class CurriculumsController < ApplicationController
  before_action :set_curriculum, only: [:show, :edit, :update, :destroy]

  # GET /curriculums
  # GET /curriculums.json
  def index
    @curriculums = Curriculum.all
  end

  # GET /curriculums/1
  # GET /curriculums/1.json
  def show
  end

  # GET /curriculums/new
  def new
    @curriculum = Curriculum.new
  end

  # GET /curriculums/1/edit
  def edit
  end

  # POST /curriculums
  # POST /curriculums.json
  def create
    @curriculum = Curriculum.new(curriculum_params)
    @curriculum.user_id = current_user.id

    respond_to do |format|
      if @curriculum.save
        format.html { redirect_to @curriculum, notice: 'Curriculum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @curriculum }
      else
        format.html { render action: 'new' }
        format.json { render json: @curriculum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /curriculums/1
  # PATCH/PUT /curriculums/1.json
  def update
    respond_to do |format|
      if @curriculum.update(curriculum_params)
        format.html { redirect_to current_user, notice: 'Curriculum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @curriculum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curriculums/1
  # DELETE /curriculums/1.json
  def destroy
    @curriculum.destroy
    respond_to do |format|
      format.html { redirect_to curriculums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curriculum
      @curriculum = Curriculum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curriculum_params
      params.require(:curriculum).permit(:description, :contact, :age, :education, :misc)
    end
end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/views/curriculums/_form.html.erb
<div class="form_holder">
<%= form_for(@curriculum) do |f| %>
  <% if @curriculum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curriculum.errors.count, "error") %> prohibited this curriculum from being saved:</h2>

      <ul>
      <% @curriculum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label "Education" %><br>
    <%= f.text_field :education, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label "Other information" %><br>
    <%= f.text_field :misc, class:'form-control' %>
  </div>
  <div class="actions centered">
    <%= f.submit "Submit Changes", class: "btn btn-large btn-custom"  %>
  </div>
<% end %>
</div>

app/views/curriculums/edit.html.erb
<h3 class="h3 centered">Editing curriculum</h3>

<%= render 'form' %>

<%= link_to 'Back', user_path, class: 'btn btn-custom back_button'  %>

app/views/curriculums/index.html.erb
<h1>Listing curriculums</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Contact</th>
      <th>Age</th>
      <th>Education</th>
      <th>Misc</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @curriculums.each do |curriculum| %>
      <tr>
        <td><%= curriculum.description %></td>
        <td><%= curriculum.contact %></td>
        <td><%= curriculum.age %></td>
        <td><%= curriculum.education %></td>
        <td><%= curriculum.misc %></td>
        <td><%= link_to 'Show', curriculum %></td>
        <td><%= link_to 'Edit', edit_curriculum_path(curriculum) %></td>
        <td><%= link_to 'Destroy', curriculum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curriculum', new_curriculum_path %>

app/views/curriculums/new.html.erb
<h1>New curriculum</h1>

<%= render 'form' %>

<%= link_to 'Back', curriculums_path %>

app/views/curriculums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @curriculum.description %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @curriculum.contact %>
</p>

<p>
  <strong>Age:</strong>
  <%= @curriculum.age %>
</p>

<p>
  <strong>Education:</strong>
  <%= @curriculum.education %>
</p>

<p>
  <strong>Misc:</strong>
  <%= @curriculum.misc %>
</p>

<%= link_to 'Edit', edit_curriculum_path(@curriculum) %> |
<%= link_to 'Back', curriculums_path %>