config/routes.rb
LetsGetPro::Application.routes.draw do

  resources :friendships

  resources :search

  resources :jobshistories

  resources :curriculums

  resources :posts

  resources :companies

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/profile/:id',  to: 'users#show',:as => :profile, via:'get'
  match '/about', to:'static_pages#about', via:'get'

  root 'posts#index', action: 'home'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_one :curriculum
  has_many :jobshistory, through: :curriculum
  has_many :friendships
  belongs_to :company, :class_name => 'Company', :foreign_key => "company_id"
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  after_create :create_default_curriculum



  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def to_param
    "#{self.id}-#{self.name}"
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

  def create_default_curriculum
    self.create_curriculum
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  layout :resolve_layout

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @friendships = @current_user.friendships.paginate(:page => params[:page], :per_page => 1)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @friendships = @user.friends.paginate(:page => params[:page], :per_page => 1)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to root_url
    else
      render 'new'
    end
  end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end


  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user

      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password_digest, :password, :password_confirmation, :workplace, :img_url,:position,:company_id)
    end

    def resolve_layout
      case action_name
        when "new","create"
          "signup"
        else
          "application"
      end
    end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-5 col-xs-offset-3">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.hidden_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :company %>
    <%= f.select :id, Company.all.collect {|e| [e.id, e.name]} %>
  </div>
  <div class="actions">
    <%= f.submit "Signup", class: "btn btn-large btn-custom" %>
  </div>
<% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div id="contacts">

  <div class="contact_notices">
    <h1 class="h1 inline_block vcenter">Contacts</h1>
    <div class="pending_requests inline_block">
      <div class="button_holder">
            <%= link_to "Pending Requests", '#potato', class: 'btn btn-sm btn-custom' %>
      </div>
    </div>
  </div>
  <div class="contact_list">
    <ul>
      <% for friendship in current_user.friendships %>
          <li><div class="contact_box">
            <img class="contact_img" src="<%= asset_path(friendship.friend.img_url)%>"/>
            <%= friendship.friend.name %>
            (<%= link_to "remove", friendship, :method => :delete %>)
          </div>
          </li>
      <% end %>
      <% for user in current_user.inverse_friends %>
          <li><div class="contact_box">
            <img class="contact_img" src="<%= asset_path(user.img_url)%>"/>
            <%= user.name %>
          </div>
          </li>
      <% end %>
    </ul>
    <div class="apple_pagination">
      <%= will_paginate @friendships, :page_links => true %>
    </div>
  </div>
 </div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!-- USER -->
  <div id="user_info" class="clear">
    <div id="user_photo_holder">
    <img id="user_photo" src="<%= asset_path(@user.img_url) %>">
    </div>
    <div id="user_text">
      <p><span class="curriculum_author_title">Name: </span><span class="curriculum_author_text"><%= @user.name %></span></p>
      <p><span class="curriculum_author_title">Employed at: </span><span class="curriculum_author_text"><%= @user.workplace %></span></p>
      <br>
      <% if  @user.curriculum.id == current_user.curriculum.id %>
      <%= link_to "Edit Curriculum", edit_curriculum_path(@user.curriculum) , class: "btn btn-sm btn-custom" %>
      <% end %>
    </div>
  </div>
  <div id="curriculum">
    <div id="curr_title">
    <p class="bold centered tall">Curriculum Vitae</p>
    <p class="bold centered"><%= @user.name %></p>
    </div>
    <br>
    <div id="curr_description" >
    <p class="justified"><%= @user.curriculum.description %></p>
    </div>
    <br>
    <div id="curr_personal" >
    <p><span class="bold">Contact:</span> <%= @user.curriculum.contact %></p>
    <p><span class="bold">Age: </span><%= @user.curriculum.age %></p>
    <p><span class="bold">Education: </span><%= @user.curriculum.education %></p>
    </div>
    <br>
    <div id="curr_pastworks">
    <p class="bold">Previous Jobs:</p>
    <div class="spacer5"></div>
      <% if  @user.curriculum.id == current_user.curriculum.id %>
    <%= link_to "Add new Job", new_jobshistory_path, class: 'btn btn-xs btn-custom' %>
       <% end %>
      <div class="spacer5"></div>
      <% @user.curriculum.jobshistories.each do |jobs| %>
          <p><%= jobs.start%>-<%= jobs.end%> <%= jobs.company%>, <%= jobs.location%>
          <% if  @user.curriculum.id == current_user.curriculum.id %>
          <%= link_to image_tag("edit_icon.png", :border => 0, :class => 'valignmiddle'), edit_jobshistory_path(jobs)%>
              <% end %></p>
    <% end %>
    </div>
  </div>
  <div id="contacts">

    <div class="contact_notices">
    <h1 class="h1 inline_block vcenter">Contacts</h1>
    <div class="pending_requests inline_block">
      <div class="button_holder">
        <% if  @user.curriculum.id == current_user.curriculum.id %>
        <%= link_to "Pending Requests", '#potato', class: 'btn btn-sm btn-custom' %>
         <% end %>
      </div>
    </div>
    </div>
    <div class="contact_list">
    <ul>
      <% for friendship in @user.friendships %>
          <li><div class="contact_box">
            <img class="contact_img" src="<%= asset_path(friendship.friend.img_url)%>"/>
            <%= friendship.friend.name %>
            <% if  @user.curriculum.id == current_user.curriculum.id %>
            (<%= link_to "remove", friendship, :method => :delete %>)
            <% end %>
          </div>
          </li>
      <% end %>
      <div class="apple_pagination">
        <%= will_paginate @friendships, :page_links => true %>
      </div>
      <% for user in @user.inverse_friends %>
          <li><div class="contact_box">
            <img class="contact_img" src="<%= asset_path(user.img_url)%>"/>
            <%= user.name %>
          </div>
          </li>
      <% end %>
    </ul>
    </div>
  </div>