config/routes.rb
LetsGetPro::Application.routes.draw do

  resources :friendships

  resources :search

  resources :jobshistories

  resources :curriculums

  resources :posts

  resources :companies

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/profile/:id',  to: 'users#show',:as => :profile, via:'get'
  match '/about', to:'static_pages#about', via:'get'

  root 'posts#index', action: 'home'

end

app/views/shared/_footer.erb
<div id ="footer"><!-- FOOTER-->
  <div id="logo">
  </div>
  <div id="validators">
    <p class="vertical_centered" style="float:left;">
      <a href="http://jigsaw.w3.org/css-validator/check/referer">
        <img style="border:0;width:88px;height:31px"
             src="http://jigsaw.w3.org/css-validator/images/vcss"
             alt="CSS válido!" />
      </a>
    </p>
    <p class="vertical_centered" style="float:left;">
      <a href="http://validator.w3.org/check?uri=https%3A%2F%2Fdl.dropboxusercontent.com%2Fu%2F16682859%2FLets%2520Go%2520Pro%2Findex.html">
        <img style="border:0;width:88px;height:31px"
             src="http://historyguild.bygbyte.org/images/html5.jpg"
             alt="HTML5 válido!" />
      </a>
    </p>

  </div>
</div><!-- END FOOTER-->

app/views/shared/_head_nav.html.erb
<div id="top_menu">
  <div id="nav_button">
    <img id="button" alt="menu icon" onclick="toggle_menu()" src="images/"/>
  </div>
  <div class="clickable_logo logo_holder">
    <p class="logo">Lets <b class="greenIncrease">GET</b> Pro</p>
  </div>

  <div id="user_details">
    <div id="user_pic">
      <img id="user_photo" alt="user pic"
           src="
            <%if current_user.img_url.nil?%>
            <%= asset_path('user.png') %>
            <% elsif Rails.application.assets.find_asset current_user.img_url  %>
           <%= asset_path(current_user.img_url) %>
            <% else  %>
            <%= current_user.img_url%>
           <% end %>
           "/>
    </div>
    <div id="info">
      <p><span class="user_title">Name: </span><span class="user_detail"><%= current_user.name %></span></p>
      <p><span class="user_title">Employed at: </span><span class="user_detail"><%= current_user.workplace %></span></p>
      <%= link_to "Signout", signout_path, method: "delete", class: 'btn btn-xs btn-custom' %>
    </div>
  </div>

  <div id="search">
    <%= form_tag search_index_path, :method => "get",class:'search_form' do %>
         <p class="col-lg-9">
            <%= text_field_tag :searchbar, params[:search], class:'form-control input-large' %>
         </p>
        <%= submit_tag "Search", :name => nil, class: 'btn btn-normal btn-custom' %>
    <% end %>
  </div>
</div>

<div id ="nav_bar">
  <ul class="centered">
    <li><%= link_to "Home", root_url %></li>
    <li><%= link_to "My Profile", profile_path(current_user.to_param) %></li>
    <li><%= link_to "Contacts", users_path %></li>
    <li>
      <% if !@current_user.company_id.nil? %>
      <%= link_to "Company Profile", company_path(@current_user.company_id) %>
      <% else %>
      <%= link_to "Company Profile", new_company_path %>
      <% end %>
    </li>
    <li><%= link_to "About Us", about_path %></li>
  </ul>
</div>

app/views/shared/_left_side_bar.html.erb
<div id="left_side_bar"> <!-- LEFT SIDE -->
  <div class="centered">
    <h3 class="bar_title">My Connections</h3>
  </div>
  <hr>
  <span class="social_title">My Company</span>
  <ul class="social_menu focusListElem">
    <li><%= link_to current_user.company.name, company_path(current_user.company_id) %></li>
  </ul>
  <span class="social_title">NEW COMPANIES</span>
  <ul class="social_menu focusListElem">
    <% Company.all.first(10).each do |company| %>
    <li>
      <%= link_to company.name, company_path(company.id) %>
    </li>
    <% end %>
  </ul>
  <span class="social_title">Groups</span>
  <ul class="social_menu focusListElem">
    <li>
      <a href="#">Hard Workers</a>
    </li>
    <li>
      <a href="#">Not So Hard Workers</a>
    </li>
    <li>
      <a href="#">The Lazy Ones</a>
    </li>
    <li>
      <a href="#">FCT-UNL</a>
    </li>
    <li>
      <a href="#">Bieber Fans</a>
    </li>
  </ul>
</div><!-- END LEFT SIDE-->

app/views/shared/_main_content.html.erb
<div id="content">
  <div id="news_feed"> <!-- NEWS FEED -->

    <div class="announce">
    <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <%= value %>
        </div>
    <% end %>
    </div>
    <%= yield %>
  </div><!-- END NEWS FEED -->
  <%= render :partial => 'shared/footer' %>
</div>

app/views/shared/_right_side_bar.html.erb
<div id="right_side_bar"><!-- RIGHT SIDE -->
  <div class="centered">
    <h3 class="bar_title">Recent News Feed</h3>
  </div>
  <hr>
  <ul id="announces" class="focusListElem">
      <% Post.all.first(5).reverse_each do |post| %>
        <li><%= link_to post.title, post_path(post) %></li>
      <% end %>
  </ul>
</div><!-- END RIGHT SIDE -->