config/routes.rb
LetsGetPro::Application.routes.draw do

  resources :friendships

  resources :search

  resources :jobshistories

  resources :curriculums

  resources :posts

  resources :companies

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/profile/:id',  to: 'users#show',:as => :profile, via:'get'
  match '/about', to:'static_pages#about', via:'get'

  root 'posts#index', action: 'home'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :user

  def to_param
    "#{self.id}-#{self.name}"
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.owner_id = current_user.id

    respond_to do |format|
      if @company.save
        current_user.update_attribute(:company_id, @company.id)
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :location, :join_date, :acronym, :tel, :website, :img_url,:description)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div class="form_holder">
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label "Since" %><br>
    <%= f.date_select :join_date, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :acronym %><br>
    <%= f.text_field :acronym, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label "Cellphone" %><br>
    <%= f.text_field :tel, class:'form-control' %>
  </div>
  <div class="field">
  <%= f.label :website %><br>
  <%= f.text_field :website, class:'form-control' %>
  </div>
  <div class="field">
   <%= f.label :description %><br>
   <%= f.text_area :description, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label "Image Url" %><br>
    <%= f.text_field :img_url, class:'form-control' %>
   </div>


  <div class="actions centered">
    <%= f.submit "Create Company", class: "btn btn-large btn-custom " %>
  </div>
<% end %>
</div>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Join date</th>
      <th>Acronym</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.location %></td>
        <td><%= company.join_date %></td>
        <td><%= company.acronym %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h3 class="h3 centered">Create New Company</h3>

<%= render 'form' %>

<%= link_to 'Back', companies_path, class:'btn btn-custom back_button' %>

app/views/companies/show.html.erb
<div id="company_info">
  <img id="company_pic" src="
  <% if @company.img_url.nil?%>
   <%= asset_path('company.png') %>
  <% elsif Rails.application.assets.find_asset @company.img_url  %>
           <%= asset_path(@company.img_url) %>
  <% else  %>
    <%= @company.img_url%>
  <% end %>
  "/>
  <div id="company_name_location">
    <p id="company_title" class="bold"><%= @company.name %></p>
    <p id="company_location_text"><%= @company.location %></p>
  </div>
</div>
<div id="company_information">
  <div id="title">
    <p class="bold">Information</p>
  </div>
  <div id="information">
    <iframe id="company_map" width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.pt/maps?ie=UTF8&amp;q=<%= @company.location %>&amp;gl=pt&amp;hq=<%= @company.location %>;radius=15000&amp;output=embed"></iframe>
    <br>
    <small><a href="https://maps.google.pt/maps?ie=UTF8&amp;q=<%= @company.location %>&amp;gl=pt&amp;hq=<%= @company.location %>" style="color:#0000FF;text-align:left">View Larger Map</a></small>
    <p id="company_text" class="justified"><%= @company.description %></p>
    <br>
    <p class="bold">Contacts:</p>
    <p><span class="bold">Telephone: </span> <%= @company.tel %></p>
    <span class="bold">Website: </span><%= link_to @company.name, "http://" + @company.website%>
  </div>
</div>
<div id="contacts">

  <div class="contact_notices">
    <h1 class="h1 inline_block vcenter">Employees</h1>
  </div>
  <div class="contact_list">
    <ul>
      <% @company.user.each do |user| %>
          <% if user.id == @company.owner_id%>

              <li><div class="contact_box strokeborder">
                <img class="contact_img" src="<%= asset_path(user.img_url)%>"/>
                <div class="floatleft">
                  <%= user.name %><br>
                  <span class="gray italic">Owner</span>
                </div>

              </div>

          <% else%>
              <li><div class="contact_box">
                <img class="contact_img" src="<%= asset_path(user.img_url)%>"/>
                <div class="floatleft">
                  <%= link_to user.name, user_path(user) %><br>
                  <span class="gray italic"><%= user.position %></span>
                </div>

              </div>
              </li>
          <% end%>
      <% end %>
    </ul>
  </div>
</div>